[package]
name = "scheduler_server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
axum = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
scheduler_core = { path = "../scheduler_core" }
