[package]
name = "scheduler-core"
version = "0.1.0"
edition = "2024"

[dependencies]
abi_stable = "0.11"
anyhow = "1"
bytes = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde-saphyr = "0.0.11"
tokio = { version = "1", features = ["net", "rt-multi-thread", "macros"] }
