[package]
name = "scheduler_encoder"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
scheduler_core = { path = "../scheduler_core" }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.9"
